export default {
  defaultTheme: "light",
  themes: {
    light: {
      colors: {
        dark: "#322414", // Closest match to primary[800]
        light: "#f1f5f9",
        white: "#ffffff",
        primary: "#bb8c57", // Closest match to primary[400]
        "on-primary": "#eee3d6", // Primary[50] for contrast
        secondary: "#5784bb", // Closest match to secondary[400]
        "on-secondary": "#d6e1ee", // Secondary[50] for contrast
        accent: "#be58ba", // Closest match to accent[400]
        "on-accent": "#f0d9ef", // Accent[50] for contrast
        success: "#198754",
        "on-success": "#fff",
        info: "#0dcaf0",
        "on-info": "#1e293b",
        warning: "#ffc107",
        "on-warning": "#1e293b",
        error: "#dc3545",
        background: "#f1f5f9",
        "on-background": "#1e293b",
        surface: "#ffffff",
        "on-surface": "#1e293b",
      },

      variables: {
        apexChartFontFamily: '"Inter", "sans-serif"',
        apexChatFontWeight: 400,
        apexChatFontSize: "12px",
        vectorMapFontSize: 13,
        vectorMapFontWeight: 600,
        vectorMapFontFamily: '"Inter", "sans-serif"',
        "code-color": "#d63384",
        "overlay-scrim-background": "#101121",
        "overlay-scrim-opacity": 0.6,
        "tooltip-background": "#1e293b",
        "hover-opacity": 0.1,
        "focus-opacity": 0.12,
        "selected-opacity": 0.06,
        "activated-opacity": 0.16,
        "pressed-opacity": 0.14,
        "dragged-opacity": 0.1,
        "disabled-opacity": 0.42,
        "border-color": "#1e293b",
        "border-opacity": 0.16,
        "high-emphasis-opacity": 0.78,
        "medium-emphasis-opacity": 0.688,
        "switch-opacity": 0.5,
        "switch-disabled-track-opacity": 0.4,
        "switch-disabled-thumb-opacity": 0.8,
        "switch-checked-disabled-opacity": 0.3,
        // Shadows
        "shadow-key-umbra-color": "#0F1422",
        "shadow-key-umbra-opacity": "rgba(var(--v-theme-on-surface), 0.06)",
        "shadow-key-penumbra-opacity": "rgba(var(--v-theme-on-surface), 0.04)",
        "shadow-key-ambient-opacity": "rgba(var(--v-theme-on-surface), 0.02)",
      },
    },

    dark: {
      colors: {
        dark: "#f1f5f9",
        light: "#1e293b",
        white: "#ffffff",
        primary: "#bb8c57",
        "on-primary": "#eee3d6",
        secondary: "#5784bb",
        "on-secondary": "#d6e1ee",
        accent: "#be58ba",
        "on-accent": "#f0d9ef",
        success: "#198754",
        "on-success": "#fff",
        info: "#0dcaf0",
        "on-info": "#1e293b",
        warning: "#ffc107",
        "on-warning": "#1e293b",
        error: "#dc3545",
        background: "#000000",
        "on-background": "#f1f5f9",
        surface: "#1e293b",
        "on-surface": "#fff",
      },

      variables: {
        apexChartFontFamily: '"Inter", "sans-serif"',
        apexChatFontWeight: 400,
        apexChatFontSize: "12px",
        vectorMapFontSize: 13,
        vectorMapFontWeight: 600,
        vectorMapFontFamily: '"Inter", "sans-serif"',
        "code-color": "#d63384",
        "overlay-scrim-background": "#32475C",
        "overlay-scrim-opacity": 0.5,
        "tooltip-background": "#f1f5f9",
        "hover-opacity": 0.1,
        "focus-opacity": 0.12,
        "selected-opacity": 0.06,
        "activated-opacity": 0.16,
        "pressed-opacity": 0.14,
        "dragged-opacity": 0.1,
        "disabled-opacity": 0.42,
        "border-color": "#f1f5f9",
        "border-opacity": 0.16,
        "high-emphasis-opacity": 0.78,
        "medium-emphasis-opacity": 0.68,
        "switch-opacity": 0.2,
        "switch-disabled-track-opacity": 0.3,
        "switch-disabled-thumb-opacity": 0.4,
        "switch-checked-disabled-opacity": 0.3,
        // Shadows
        "shadow-key-umbra-color": "#2F2B3D",
        "shadow-key-umbra-opacity": "rgba(var(--v-theme-on-surface), 0.06)",
        "shadow-key-penumbra-opacity": "rgba(var(--v-theme-on-surface), 0.04)",
        "shadow-key-ambient-opacity": "rgba(var(--v-theme-on-surface), 0.02)",
      },
    },
  },
};
